### PR TITLE
Copy the data when merge into single ngram.

### LINKED ISSUE #118: Segementation fault with certain user data after normal usage with libzhuyin.
The issue itself definitely related certain user data. I have no idea whether the data file is corruptted or libzhuyin generates some invalid file, so I uploaded both the user and system data for testing. Please update path in test code correspondingly to reproduce it. This is not the first time I hit the similar issue and last time I just remove the user data. So I doubt it is really related to data corruption.

[user_zhuyin.tar.gz](https://github.com/libpinyin/libpinyin/files/5081700/user_zhuyin.tar.gz)
[system_zhuyin.tar.gz](https://github.com/libpinyin/libpinyin/files/5081701/system_zhuyin.tar.gz)

```
#include <zhuyin.h>
#include <iostream>

using namespace std;

int main() {
    auto c = zhuyin_init("......", "...........");
    zhuyin_set_options(c, USE_TONE | ZHUYIN_CORRECT_ALL);
    zhuyin_set_full_pinyin_scheme(c, FULL_PINYIN_HANYU);
    auto i = zhuyin_alloc_instance(c);
    char* s;
    zhuyin_parse_more_full_pinyins(i, "barenfei");
    zhuyin_guess_sentence(i);
    zhuyin_get_sentence(i, &s);
    return 0;
}
```

valgrind log FYI:

==86630== Memcheck, a memory error detector
==86630== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==86630== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==86630== Command: ./a.out
==86630== 
==86630== Invalid write of size 4
==86630==    at 0x48D9B9A: set_content (memory_chunk.h:287)
==86630==    by 0x48D9B9A: pinyin::merge_single_gram(pinyin::SingleGram*, pinyin::SingleGram const*, pinyin::SingleGram const*) (ngram.cpp:306)
==86630==    by 0x48C44AE: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:597)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630==  Address 0x5f6bc00 is 0 bytes inside a block of size 17,532 free'd
==86630==    at 0x483BD7B: realloc (vg_replace_malloc.c:834)
==86630==    by 0x492E2F6: ensure_has_more_space (memory_chunk.h:122)
==86630==    by 0x492E2F6: ensure_has_space (memory_chunk.h:92)
==86630==    by 0x492E2F6: set_size (memory_chunk.h:221)
==86630==    by 0x492E2F6: pinyin::Bigram::load(unsigned int, pinyin::SingleGram*&, bool) (ngram_kyotodb.cpp:124)
==86630==    by 0x48C4479: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:594)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630==  Block was alloc'd at
==86630==    at 0x483977F: malloc (vg_replace_malloc.c:307)
==86630==    by 0x492E170: ensure_has_more_space (memory_chunk.h:104)
==86630==    by 0x492E170: ensure_has_space (memory_chunk.h:92)
==86630==    by 0x492E170: set_size (memory_chunk.h:221)
==86630==    by 0x492E170: pinyin::Bigram::load(unsigned int, pinyin::SingleGram*&, bool) (ngram_kyotodb.cpp:124)
==86630==    by 0x48C4479: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:594)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630== 
==86630== Invalid read of size 2
==86630==    at 0x4840600: memmove (vg_replace_strmem.c:1270)
==86630==    by 0x48D9546: pinyin::MemoryChunk::ensure_has_more_space(unsigned long) (memory_chunk.h:107)
==86630==    by 0x48D9D4A: ensure_has_space (memory_chunk.h:92)
==86630==    by 0x48D9D4A: set_content (memory_chunk.h:286)
==86630==    by 0x48D9D4A: append_content (memory_chunk.h:302)
==86630==    by 0x48D9D4A: pinyin::merge_single_gram(pinyin::SingleGram*, pinyin::SingleGram const*, pinyin::SingleGram const*) (ngram.cpp:322)
==86630==    by 0x48C44AE: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:597)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630==  Address 0x5f6bc00 is 0 bytes inside a block of size 17,532 free'd
==86630==    at 0x483BD7B: realloc (vg_replace_malloc.c:834)
==86630==    by 0x492E2F6: ensure_has_more_space (memory_chunk.h:122)
==86630==    by 0x492E2F6: ensure_has_space (memory_chunk.h:92)
==86630==    by 0x492E2F6: set_size (memory_chunk.h:221)
==86630==    by 0x492E2F6: pinyin::Bigram::load(unsigned int, pinyin::SingleGram*&, bool) (ngram_kyotodb.cpp:124)
==86630==    by 0x48C4479: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:594)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630==  Block was alloc'd at
==86630==    at 0x483977F: malloc (vg_replace_malloc.c:307)
==86630==    by 0x492E170: ensure_has_more_space (memory_chunk.h:104)
==86630==    by 0x492E170: ensure_has_space (memory_chunk.h:92)
==86630==    by 0x492E170: set_size (memory_chunk.h:221)
==86630==    by 0x492E170: pinyin::Bigram::load(unsigned int, pinyin::SingleGram*&, bool) (ngram_kyotodb.cpp:124)
==86630==    by 0x48C4479: pinyin::PhoneticLookup<1, 1>::search_bigram2(_GPtrArray*, int, int, _GArray**) (phonetic_lookup.h:594)
==86630==    by 0x48C5641: pinyin::PhoneticLookup<1, 1>::get_nbest_match(_GArray*, pinyin::PhoneticKeyMatrix const*, pinyin::ForwardPhoneticConstraints const*, pinyin::NBestMatchResults*) (phonetic_lookup.h:808)
==86630==    by 0x48C28B8: zhuyin_guess_sentence (zhuyin.cpp:904)
==86630==    by 0x1092A8: main (2.cc:13)
==86630==

### PR DESCRIPTION
**Pull request by wengxt**
system and user might be invalidated later.

Fix #118

### CODE REVIEW

File: src/storage/ngram.cpp [hunk 1]
```diff
@@ -284,14 +284,14 @@ bool merge_single_gram(SingleGram * merged, const SingleGram * system,
     MemoryChunk & merged_chunk = merged->m_chunk;
 
     if (NULL == system) {
-        merged_chunk.set_chunk(user->m_chunk.begin(),
-                               user->m_chunk.size(), NULL);
+        merged_chunk.set_content(0, user->m_chunk.begin(),
+				 user->m_chunk.size());
```
Comment (epico) [inline src/storage/ngram.cpp:288]: Please use the space key instead of tab key...

File: src/storage/ngram.cpp [hunk 2]
```diff
@@ -284,14 +284,14 @@ bool merge_single_gram(SingleGram * merged, const SingleGram * system,
...
         return true;
     }
 
     if (NULL == user) {
-        merged_chunk.set_chunk(system->m_chunk.begin(),
-                               system->m_chunk.size(), NULL);
+        merged_chunk.set_content(0, system->m_chunk.begin(),
+				 system->m_chunk.size());
```
Comment (epico) [inline src/storage/ngram.cpp:294]: The same as above...

**Comment by epico** [comment]
Thanks, patch merged!
